## RUN COMMAND
## docker-compose up -d

version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: barca
      POSTGRES_PASSWORD: barca
      POSTGRES_DB: barca,
      POSTGRES_HOST: 0.0.0.0
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
